### ISSUE TITLE
Build fails on ubuntu18.04

### ISSUE THREAD

**Issue by moonshaadow** [RomanKubiak/ctrlr#253]

**Comment by moonshaadow** [comment]
Hi there.
I can't build on Ubuntu 18.04.
First I have to re-save with the projucer in order to have a correct makefile. (without that, make fails at start)

Then I can start to compile with `post-commit`, but I've got several errors ( related to `bfd`), when compiling `libr.c` :

```
$ ./post-commit
CTRLR pre-commit HOOK
CTRLR: distro detected as Ubuntu, check packages
	[g++:ok]
	[libxrandr-dev:ok]
	[libxinerama-dev:ok]
	[libxcursor-dev:ok]
	[libasound2-dev:ok]
	[binutils-dev:ok]
	[libfreetype6-dev:ok]
	[xorg-dev:ok]
	[libgl1-mesa-dev:ok]
	[libglapi-mesa:ok]
	[libxrandr-dev:ok]
	[libudev-dev:ok]
	[libgl1-mesa-dev:ok]
	[libiberty-dev:ok]
CTRLR: build_now_linux
CTRLR: CTRLR_ROOT /home/studio/Bureau/git_things/ctrlr/Scripts/../
----------------------------------------
	Version: 5.6.23
	CtrlrRevision.template: /home/studio/Bureau/git_things/ctrlr/Scripts/..//Source/Core/CtrlrRevision.template
	CtrlrRevision.h: /home/studio/Bureau/git_things/ctrlr/Scripts/..//Source/Core/CtrlrRevision.h
	Date: mardi 13 avril 2021, 13:13:59 (UTC+0200)
----------------------------------------
CTRLR: Delete binaries
CTRLR: check if boost is unpacked
CTRLR: boot directory exists
CTRLR: Build Standalone
CTRLR[linux]: Building for x86_64, JOBS 8
Compiling include_juce_audio_plugin_client_VST2.cpp
Compiling class.cpp
Compiling class_info.cpp
Compiling class_registry.cpp
Compiling class_rep.cpp
Compiling create_class.cpp
Compiling error.cpp
Compiling exception_handler.cpp
Compiling function.cpp
Compiling function_introspection.cpp
Compiling inheritance.cpp
Compiling link_compatibility.cpp
Compiling lua51compat.cpp
Compiling object_rep.cpp
Compiling open.cpp
Compiling operator.cpp
Compiling pcall.cpp
Compiling scope.cpp
Compiling set_package_preload.cpp
Compiling shared_ptr_converter.cpp
Compiling stack_content_by_name.cpp
Compiling weak_ref.cpp
Compiling wrapper_base.cpp
Compiling compat.c
Compiling core.c
Compiling darwin_usb.c
Compiling descriptor.c
Compiling enums.c
Compiling hotplug.c
Compiling io.c
Compiling linux_udev.c
Compiling linux_usbfs.c
Compiling poll_posix.c
Compiling poll_windows.c
Compiling strerror.c
Compiling structs.c
Compiling sync.c
Compiling threads_posix.c
Compiling threads_windows.c
Compiling usb.c
Compiling windows_usb.c
Compiling lua.c
Compiling keys.cpp
Compiling libr-bfd.c
Compiling libr.c
../../Source/Misc/libr-bfd.c: In function ‘keep_symbol’:
../../Source/Misc/libr-bfd.c:111:28: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
  111 |     bfd_section_size(chkscn) == 0
      |                            ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:302: note: macro "bfd_section_size" defined here
  302 | #define bfd_section_size(bfd, ptr) ((ptr)->size)
      | 
../../Source/Misc/libr-bfd.c:111:5: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
  111 |     bfd_section_size(chkscn) == 0
      |     ^~~~~~~~~~~~~~~~
      |     bfd_set_gp_size
../../Source/Misc/libr-bfd.c:111:5: note: each undeclared identifier is reported only once for each function it appears in
../../Source/Misc/libr-bfd.c: In function ‘setup_sections’:
../../Source/Misc/libr-bfd.c:168:25: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
  168 |    bfd_section_size(iscn) == 0
      |                         ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:302: note: macro "bfd_section_size" defined here
  302 | #define bfd_section_size(bfd, ptr) ((ptr)->size)
      | 
../../Source/Misc/libr-bfd.c:168:4: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
  168 |    bfd_section_size(iscn) == 0
      |    ^~~~~~~~~~~~~~~~
      |    bfd_set_gp_size
../../Source/Misc/libr-bfd.c:196:5: error: too few arguments to function ‘bfd_set_section_size’
  196 |    !bfd_set_section_size(oscn, iscn->size)
      |     ^~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1906:13: note: declared here
 1906 | bfd_boolean bfd_set_section_size
      |             ^~~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c:206:29: error: macro "bfd_section_vma" requires 2 arguments, but only 1 given
  206 |   vma = bfd_section_vma(iscn);
      |                             ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:304: note: macro "bfd_section_vma" defined here
  304 | #define bfd_section_vma(bfd, ptr) ((ptr)->vma)
      | 
../../Source/Misc/libr-bfd.c:206:9: error: ‘bfd_section_vma’ undeclared (first use in this function); did you mean ‘bfd_scan_vma’?
  206 |   vma = bfd_section_vma(iscn);
      |         ^~~~~~~~~~~~~~~
      |         bfd_scan_vma
../../Source/Misc/libr-bfd.c:212:5: error: too few arguments to function ‘bfd_set_section_vma’
  212 |    !bfd_set_section_vma(oscn, vma)
      |     ^~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1675:1: note: declared here
 1675 | bfd_set_section_vma (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr, bfd_vma val)
      | ^~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c:224:63: error: macro "bfd_section_alignment" requires 2 arguments, but only 1 given
  224 |    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
      |                                                               ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:306: note: macro "bfd_section_alignment" defined here
  306 | #define bfd_section_alignment(bfd, ptr) ((ptr)->alignment_power)
      | 
../../Source/Misc/libr-bfd.c:224:37: error: ‘bfd_section_alignment’ undeclared (first use in this function); did you mean ‘bfd_set_section_alignment’?
  224 |    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
      |                                     ^~~~~~~~~~~~~~~~~~~~~
      |                                     bfd_set_section_alignment
../../Source/Misc/libr-bfd.c:224:5: error: too few arguments to function ‘bfd_set_section_alignment’
  224 |    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1683:1: note: declared here
 1683 | bfd_set_section_alignment (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c: In function ‘build_output’:
../../Source/Misc/libr-bfd.c:301:31: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
  301 |   size = bfd_section_size(iscn);
      |                               ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:302: note: macro "bfd_section_size" defined here
  302 | #define bfd_section_size(bfd, ptr) ((ptr)->size)
      | 
../../Source/Misc/libr-bfd.c:301:10: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
  301 |   size = bfd_section_size(iscn);
      |          ^~~~~~~~~~~~~~~~
      |          bfd_set_gp_size
Compiling CtrlrManager.cpp
../../Source/Misc/libr-bfd.c: In function ‘add_section’:
../../Source/Misc/libr-bfd.c:566:4: error: too few arguments to function ‘bfd_set_section_flags’
  566 |   !bfd_set_section_flags(scn, SEC_HAS_CONTENTS | SEC_DATA | SEC_IN_MEMORY)
      |    ^~~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1890:13: note: declared here
 1890 | bfd_boolean bfd_set_section_flags
      |             ^~~~~~~~~~~~~~~~~~~~~
make: *** [build/intermediate/Release/libr-bfd_fc7a9004.o] Error 1
make: *** Attente des tâches non terminées....
Makefile:607: recipe for target 'build/intermediate/Release/libr-bfd_fc7a9004.o' failed
CTRLR[linux]: build failed

CTRLR[linux]: Building for x86_64, JOBS 8
Compiling libr-bfd.c
Compiling CtrlrManagerInstance.cpp
Compiling CtrlrManagerVst.cpp
Compiling CtrlrModulator.cpp
Compiling CtrlrModulatorProcessor.cpp
Compiling CtrlrEvaluationScopes.cpp
Compiling CtrlrPanel.cpp
Compiling CtrlrPanelFileOperations.cpp
../../Source/Misc/libr-bfd.c: In function ‘keep_symbol’:
../../Source/Misc/libr-bfd.c:111:28: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
  111 |     bfd_section_size(chkscn) == 0
      |                            ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:302: note: macro "bfd_section_size" defined here
  302 | #define bfd_section_size(bfd, ptr) ((ptr)->size)
      | 
../../Source/Misc/libr-bfd.c:111:5: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
  111 |     bfd_section_size(chkscn) == 0
      |     ^~~~~~~~~~~~~~~~
      |     bfd_set_gp_size
../../Source/Misc/libr-bfd.c:111:5: note: each undeclared identifier is reported only once for each function it appears in
../../Source/Misc/libr-bfd.c: In function ‘setup_sections’:
../../Source/Misc/libr-bfd.c:168:25: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
  168 |    bfd_section_size(iscn) == 0
      |                         ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:302: note: macro "bfd_section_size" defined here
  302 | #define bfd_section_size(bfd, ptr) ((ptr)->size)
      | 
../../Source/Misc/libr-bfd.c:168:4: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
  168 |    bfd_section_size(iscn) == 0
      |    ^~~~~~~~~~~~~~~~
      |    bfd_set_gp_size
../../Source/Misc/libr-bfd.c:196:5: error: too few arguments to function ‘bfd_set_section_size’
  196 |    !bfd_set_section_size(oscn, iscn->size)
      |     ^~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1906:13: note: declared here
 1906 | bfd_boolean bfd_set_section_size
      |             ^~~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c:206:29: error: macro "bfd_section_vma" requires 2 arguments, but only 1 given
  206 |   vma = bfd_section_vma(iscn);
      |                             ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:304: note: macro "bfd_section_vma" defined here
  304 | #define bfd_section_vma(bfd, ptr) ((ptr)->vma)
      | 
../../Source/Misc/libr-bfd.c:206:9: error: ‘bfd_section_vma’ undeclared (first use in this function); did you mean ‘bfd_scan_vma’?
  206 |   vma = bfd_section_vma(iscn);
      |         ^~~~~~~~~~~~~~~
      |         bfd_scan_vma
../../Source/Misc/libr-bfd.c:212:5: error: too few arguments to function ‘bfd_set_section_vma’
  212 |    !bfd_set_section_vma(oscn, vma)
      |     ^~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1675:1: note: declared here
 1675 | bfd_set_section_vma (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr, bfd_vma val)
      | ^~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c:224:63: error: macro "bfd_section_alignment" requires 2 arguments, but only 1 given
  224 |    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
      |                                                               ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:306: note: macro "bfd_section_alignment" defined here
  306 | #define bfd_section_alignment(bfd, ptr) ((ptr)->alignment_power)
      | 
../../Source/Misc/libr-bfd.c:224:37: error: ‘bfd_section_alignment’ undeclared (first use in this function); did you mean ‘bfd_set_section_alignment’?
  224 |    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
      |                                     ^~~~~~~~~~~~~~~~~~~~~
      |                                     bfd_set_section_alignment
../../Source/Misc/libr-bfd.c:224:5: error: too few arguments to function ‘bfd_set_section_alignment’
  224 |    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1683:1: note: declared here
 1683 | bfd_set_section_alignment (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c: In function ‘build_output’:
../../Source/Misc/libr-bfd.c:301:31: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
  301 |   size = bfd_section_size(iscn);
      |                               ^
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:302: note: macro "bfd_section_size" defined here
  302 | #define bfd_section_size(bfd, ptr) ((ptr)->size)
      | 
../../Source/Misc/libr-bfd.c:301:10: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
  301 |   size = bfd_section_size(iscn);
      |          ^~~~~~~~~~~~~~~~
      |          bfd_set_gp_size
../../Source/Misc/libr-bfd.c: In function ‘add_section’:
../../Source/Misc/libr-bfd.c:566:4: error: too few arguments to function ‘bfd_set_section_flags’
  566 |   !bfd_set_section_flags(scn, SEC_HAS_CONTENTS | SEC_DATA | SEC_IN_MEMORY)
      |    ^~~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:124,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1890:13: note: declared here
 1890 | bfd_boolean bfd_set_section_flags
      |             ^~~~~~~~~~~~~~~~~~~~~
make: *** [build/intermediate/Release/libr-bfd_fc7a9004.o] Error 1
Makefile:607: recipe for target 'build/intermediate/Release/libr-bfd_fc7a9004.o' failed
make: *** Attente des tâches non terminées....
CTRLR[linux]: build failed

CTRLR: Clean old package files
CTRLR: copy files for package
cp: impossible d'évaluer '/home/studio/Bureau/git_things/ctrlr/Scripts/..//Builds/LinuxMakefile/build/Ctrlr': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer '/home/studio/Bureau/git_things/ctrlr/Scripts/..//Builds/LinuxMakefile/build/Ctrlr.so': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer '/home/studio/Bureau/git_things/ctrlr/Scripts/..//Builds/LinuxMakefile/build/Ctrlr.vst3': Aucun fichier ou dossier de ce type
CTRLR: strip binaries
strip: « /home/studio/Bureau/git_things/ctrlr/Scripts/..//Packaging/Linux/Ctrlr/Ctrlr »: pas de tel fichier
strip: « /home/studio/Bureau/git_things/ctrlr/Scripts/..//Packaging/Linux/Ctrlr/Ctrlr.so »: pas de tel fichier
strip: « /home/studio/Bureau/git_things/ctrlr/Scripts/..//Packaging/Linux/Ctrlr/Ctrlr.vst3/Contents/x86_64-linux/Ctrlr.so »: pas de tel fichier
CTRLR: create self extracting package
Header is 402 lines long

About to compress 672 KB of data...
Adding files to archive named "/home/studio/Bureau/git_things/ctrlr/Scripts/..//Packaging/Linux/Ctrlr-x86_64-5.6.23.sh"...
./
./Panels/
./Doc/
./Doc/ctrlr_red.ico
./Doc/ctrlr_black.xcf
./Doc/gpl.txt
./Doc/Ctrlr.overrides
./Doc/lua.txt
./Doc/ctrlr.doxygen
./Doc/Licenses/
./Doc/Licenses/69sekuntia/
./Doc/Licenses/69sekuntia/readme.txt
./Doc/Licenses/LCDWinTT/
./Doc/Licenses/LCDWinTT/README.TXT
./Doc/Licenses/LCDWinTT/LICENSE.TXT
./Doc/Licenses/Digital-7/
./Doc/Licenses/Digital-7/README.TXT
./Doc/Licenses/LCDMonoWinTT/
./Doc/Licenses/LCDMonoWinTT/README.TXT
./Doc/Licenses/LCDMonoWinTT/LICENSE.TXT
CRC: 2407262140
MD5: 1a735d608d272c624996d88bd7398767

Self-extractible archive "/home/studio/Bureau/git_things/ctrlr/Scripts/..//Packaging/Linux/Ctrlr-x86_64-5.6.23.sh" successfully created.
```

**Comment by gavocanov** [comment]
Install the `binutils-dev` package, should solve your problem.

**Comment by dromer** [comment]
Same issue on Debian Buster. `binutils-dev` package is not enough to overcome this.

**Comment by shooking** [comment]
Look at the bfd code - I think the 18.0 is not suing 2.34 or whatever the default now is. I am reasonably sure this type of issue is reported in earlier issues.

**Comment by RomanKubiak** [comment]
there was an issue with binutils-dev version  i'm trying to fix it, a branch kiosk should solve this for if building with build.sh

**Comment by dromer** [comment]
@RomanKubiak trying the `kiosk` branch the build now does succeed, however trying to execute Ctrlr results in:
```
./Ctrlr() [0x898bfb]
./Ctrlr() [0x7862fa]
./Ctrlr() [0x898e4a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7faab616b730]
./Ctrlr() [0x79f8f4]
./Ctrlr() [0xbf6f99]
./Ctrlr() [0x93acf9]
./Ctrlr() [0x945756]
./Ctrlr() [0x941a5b]
./Ctrlr() [0x938c97]
./Ctrlr() [0x938a8a]
./Ctrlr() [0xa1d462]
./Ctrlr() [0xb484a3]
./Ctrlr() [0xb48386]
./Ctrlr() [0xac68cf]
./Ctrlr() [0xceaba3]
./Ctrlr() [0xbeb5ec]
./Ctrlr() [0xbeb063]
./Ctrlr() [0xbda578]
./Ctrlr() [0xbdac55]
./Ctrlr() [0xbdaf90]
./Ctrlr() [0x79da43]
./Ctrlr() [0x7869d2]
./Ctrlr() [0x785a0d]
./Ctrlr() [0x937f84]
./Ctrlr() [0x937d12]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7faab57cf09b]
./Ctrlr() [0x7852da]
```

**Comment by keinstein** [comment]
@RomanKubiak you cant fix the binutils-dev version. It is not meant to be linked dynamically against anything than binutils. The libraries must be linked statically.

**Comment by Taikakim** [comment]
So is there way to make Ctrlr work on Linux at all? None of the three versions I tried worked. I also compiled and installed binutils myself, and installed the binutils-dev package, I'm still getting the error : `./Ctrlr: error while loading shared libraries: libbfd-2.34-system.so: cannot open shared object file: No such file or directory`

**Comment by keinstein** [comment]
This is a well-known bug in the Ctrlr build system.
libbfd *must* *not* be linked dynamically into Ctrlr. But even if you build Ctrlr yourself chances are high that it crashes as it builds against an outdated version of libusb.
You can try https://github.com/keinstein/ctrlr/releases/tag/build-2023-01-24 . It is built on debian testing/unstable and tries to fix these issues. I just got the code to compile so no warranty.

**Comment by Taikakim** [comment]
Thanks, I'll try that! Only the source files are downloadable, for the .deb I'm getting a:
```
Error 503 Backend unavailable, connection timeout

Backend unavailable, connection timeout
Error 54113

Details: cache-hel1410025-HEL 1674637000 766903754
```

**Comment by keinstein** [comment]
I tried it just now, and it worked. Maybe some issue with GitHub?
