### ISSUE TITLE
Plugin-Version sending Midimessages twice

### ISSUE THREAD

**Issue by Possemo** [RomanKubiak/ctrlr#33]
As far as I know this happens on all plugin versions (Win vst, Mac au, Mac vst). When sending Midimessages by Lua code this bug does not show (it will send messages once). So I guess it must be a bug of the Midi-Component.

Example1, IPR sysexmessage. Moving from value 00 to 06:

[09:52:44:000510]: RAW:[f0 41 39 00 24 30 01 12 00 f7]
[09:52:44:000510]: RAW:[f0 41 39 00 24 30 01 12 00 f7]
[09:52:58:000142]: RAW:[f0 41 39 00 24 30 01 12 01 f7]
[09:52:58:000142]: RAW:[f0 41 39 00 24 30 01 12 01 f7]
[09:52:59:000251]: RAW:[f0 41 39 00 24 30 01 12 02 f7]
[09:52:59:000251]: RAW:[f0 41 39 00 24 30 01 12 02 f7]
[09:52:59:000902]: RAW:[f0 41 39 00 24 30 01 12 03 f7]
[09:52:59:000902]: RAW:[f0 41 39 00 24 30 01 12 03 f7]
[09:53:00:000659]: RAW:[f0 41 39 00 24 30 01 12 04 f7]
[09:53:00:000659]: RAW:[f0 41 39 00 24 30 01 12 04 f7]
[09:53:02:000782]: RAW:[f0 41 39 00 24 30 01 12 05 f7]
[09:53:02:000782]: RAW:[f0 41 39 00 24 30 01 12 05 f7]
[09:53:04:000104]: RAW:[f0 41 39 00 24 30 01 12 06 f7]
[09:53:04:000104]: RAW:[f0 41 39 00 24 30 01 12 06 f7]

Example2, APR sysexmessage. Sent by a Lua script, no doubled messages:

[09:54:52:000798]: RAW:[f0 41 38 00 24 30 01 20 20 4c 4f 57 20 53 54 52 49 4e 47 20 50 41 44 20 20 06 4c 27 26 00 00 00 7f 14 1c 2d 09 00 00 4e 00 02 00 01 00 09 00 00 4c 01 7e 00 01 00 5a 01 1a 00 00 00 f7]

[09:54:52:000798]: RAW:[f0 41 38 00 24 20 01 20 53 54 52 49 4e 47 53 20 31 20 38 05 00 38 32 00 00 40 00 00 40 00 00 7f 7f 00 3c 00 00 00 02 67 69 43 67 00 00 00 00 00 00 00 00 00 00 00 00 7f 00 7f 00 7f 00 29 4b 00 34 58 56 24 48 00 00 00 60 00 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 50 60 50 50 40 60 40 20 00 20 00 00 00 00 20 00 00 f7]

[09:54:52:000798]: RAW:[f0 41 38 00 24 20 02 4c 4f 20 53 54 52 49 4e 47 53 20 38 05 00 38 48 00 00 40 00 00 40 00 00 7f 7f 00 3c 00 00 00 14 67 7f 43 61 00 00 00 00 00 00 00 00 00 00 00 00 7f 00 7f 00 7f 00 00 46 00 34 58 56 24 48 00 00 00 60 00 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 50 50 60 50 50 40 60 40 20 00 20 00 00 00 00 20 00 00 f7]

Just to show you that this is not a bug of the Midimonitor: Reaper and MidiOX connected through loopMIDI. MidiOX display:

```
 TIMESTAMP IN PORT STATUS DATA1 DATA2 CHAN NOTE EVENT               
 0000E9DA   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 01 F7
 0000E9DA   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 01 F7
 0001043A   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 02 F7
 0001043A   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 02 F7
 00010A84   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 03 F7
 00010A84   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 03 F7
 00010E44   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 04 F7
 00010E44   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 04 F7
 000111AF   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 05 F7
 000111AF   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 05 F7
 000115BA   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 06 F7
 000115BA   9  --     F0  Buffer:    10 Bytes   System Exclusive      
 SYSX: F0 41 39 00 24 30 01 12 06 F7
```

**Comment by Possemo** [comment]
I found out that this only happens when using "output to pluginhost" instead of configuring a midi out port. "output to pluginhost" would be the much better way as it doesnt't lock the port so it stays available in the DAW.

**Comment by RomanKubiak** [comment]
i think i fixed this issue, so the next release build should have it fixed

**Comment by dobo365** [comment]
Isn't this the same issue (or a related one) to https://ctrlr.org/forums/topic/midimessagereceived-executed-2-times/ ?
The issue was for the standalone version and I solved it by resetting the Input devices at panel load and this is working fine (no double execution of MidiMessageReceived for one message and bidi is OK):

```
-- Reset Midi INPUT devices to avoid having MidiMessageReceived method called twice
-- If resetting Controller devices then the bidirectional behaviour is lost (most probably a bug)
sMidiDevices = panel:getProperty("panelMidiInputDevice")
panel:setPropertyString("panelMidiInputDevice", "-- None")
panel:setPropertyString("panelMidiInputDevice", sMidiDevices)
```

@Possemo mentioned my fix above working well in standalone didn't solve the issue in the VST version.

**Comment by Possemo** [comment]
No, this is another issue - only happens with vst plugin. There are not a lot of DAW's where "output to pluginhost" is working anyway. Reaper is one of them.

**Comment by Possemo** [comment]
I have just checked it with the newest ver 6.0.26:
vsti v2 x64 = bug ist still there
vsti v3       = feature does not seem work at all (output to pluginhost)

As Reaper is one of the very few DAW's where this does work halfways I'd suggest to remove it (input from plugin host, input from pluginhost to comparator, output to pluginhost). Also all MIDI-Thru pluginhost related entries.Btw. I have tested it with restricted instances.

**Comment by Possemo** [comment]
Ok, as I am finally able to build with vs2019 I could see that you are right Roman. With vsti v2.4 this is finally working perfectly, no doubly messages anymore.

It seems that with vsti v3 this is not working, It looks like it does not pass sysex, both input and output. Maybe it is the DAW (Reaper) who does it wrong. There's happening weird things when looking at the output. Instead of sysex it sends all kinds of MIDI events - cc, noteoff, program change... but not sysex as it should. 

As this is another issue I am closing this one here.
